
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.proyecto1_compi1_1s_2026.backend.generate.pkm;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SLASH_GT = 48;
  public static final int COLOR_HSL = 42;
  public static final int FONT_FAMILY_KEY = 30;
  public static final int METADATA_DELIM = 2;
  public static final int DESCRIPTION = 6;
  public static final int STRING_TEXT = 57;
  public static final int TOTAL_PREGUNTAS = 8;
  public static final int SLASH = 52;
  public static final int EQUALS = 49;
  public static final int COLOR_KEY = 28;
  public static final int MONO = 35;
  public static final int TEXTOS = 14;
  public static final int FECHA = 4;
  public static final int STRING_END = 56;
  public static final int LT_SLASH = 47;
  public static final int HORIZONTAL = 34;
  public static final int LT = 45;
  public static final int TOTAL_SECCIONES = 7;
  public static final int COMMA = 50;
  public static final int CURSIVE = 37;
  public static final int SELECT = 26;
  public static final int STRING_START = 55;
  public static final int VERTICAL = 33;
  public static final int COLOR_HEX = 40;
  public static final int BOOLEAN = 39;
  public static final int EOF = 0;
  public static final int TEXT_SIZE_KEY = 31;
  public static final int TABLE = 21;
  public static final int DRAWS_EJECUTADOS = 17;
  public static final int error = 1;
  public static final int LINE = 22;
  public static final int TOTAL_COMPONENTES = 13;
  public static final int NUMBER = 43;
  public static final int BORDER_STYLE = 38;
  public static final int MULTIPLE = 27;
  public static final int MULTIPLES = 12;
  public static final int SELECCION = 11;
  public static final int COLON = 51;
  public static final int LBRACE = 53;
  public static final int CONTENT = 20;
  public static final int EMOJI_SPEC = 58;
  public static final int BACKGROUND_COLOR_KEY = 29;
  public static final int AUTHOR = 3;
  public static final int TABLAS = 15;
  public static final int ELEMENT = 23;
  public static final int DROP = 25;
  public static final int RBRACE = 54;
  public static final int SANS_SERIF = 36;
  public static final int OPEN = 24;
  public static final int CON_ESTILOS = 16;
  public static final int COLOR_RGB = 41;
  public static final int ABIERTAS = 9;
  public static final int SECTION = 18;
  public static final int STYLE = 19;
  public static final int GT = 46;
  public static final int DESPLEGABLES = 10;
  public static final int HORA = 5;
  public static final int BORDER_KEY = 32;
  public static final int IDENTIFIER = 44;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "METADATA_DELIM",
  "AUTHOR",
  "FECHA",
  "HORA",
  "DESCRIPTION",
  "TOTAL_SECCIONES",
  "TOTAL_PREGUNTAS",
  "ABIERTAS",
  "DESPLEGABLES",
  "SELECCION",
  "MULTIPLES",
  "TOTAL_COMPONENTES",
  "TEXTOS",
  "TABLAS",
  "CON_ESTILOS",
  "DRAWS_EJECUTADOS",
  "SECTION",
  "STYLE",
  "CONTENT",
  "TABLE",
  "LINE",
  "ELEMENT",
  "OPEN",
  "DROP",
  "SELECT",
  "MULTIPLE",
  "COLOR_KEY",
  "BACKGROUND_COLOR_KEY",
  "FONT_FAMILY_KEY",
  "TEXT_SIZE_KEY",
  "BORDER_KEY",
  "VERTICAL",
  "HORIZONTAL",
  "MONO",
  "SANS_SERIF",
  "CURSIVE",
  "BORDER_STYLE",
  "BOOLEAN",
  "COLOR_HEX",
  "COLOR_RGB",
  "COLOR_HSL",
  "NUMBER",
  "IDENTIFIER",
  "LT",
  "GT",
  "LT_SLASH",
  "SLASH_GT",
  "EQUALS",
  "COMMA",
  "COLON",
  "SLASH",
  "LBRACE",
  "RBRACE",
  "STRING_START",
  "STRING_END",
  "STRING_TEXT",
  "EMOJI_SPEC"
  };
}

